### PR TITLE
feat/monorepo-073

### PR DESCRIPTION
**Pull request by SerSerch**
React Native New Architecture 0.73.6
+ yarn 4
+ monorepo
+ typescript
+ turbo expo
+ lerna
+ eslint
+ prettier
+ jest

### CODE REVIEW

**Comment by SerSerch** [comment]
maybe someone else will help to understand turbo expo
```
cd ./monorepo/examples/turbo-expo
npx expo install react-native-turbo-monorepo
yarn android
```

**Comment by cortinico** [comment]
Closing as this kind of change is a bit too invasive. We don't want to maintain a full monorepo example

**Comment by SerSerch** [comment]
@cortinico Ok. 
I thought it would be useful for those who make monorepo. Because I spent a whole week dealing with it and all the information on the Internet is outdated.

If necessary I can make an [example typescript event emitter with 073 version](https://github.com/serserm/RNNewArchitectureLibraries/tree/feat/typescript-event-emitter-073).
I also had problems with this, I was looking for a solution for a long time.

**Comment by cortinico** [comment]
> I thought it would be useful for those who make monorepo. Because I spent a whole week dealing with it and all the information on the Internet is outdated.

It definitely is useful, but the best would be for you to host the sample app on your account and share it with the rest of the community.

**Pull request closed without merging**
